export const JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET';
export const JWT_ACCESS_EXPIRES_IN = 'JWT_ACCESS_EXPIRES_IN';

export const JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET';
export const JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN';

export const OPENAI_API_KEY = 'OPENAI_API_KEY';
export const BUNNY_CDN_STORAGE_URL = 'BUNNY_CDN_STORAGE_URL';
export const BUNNY_CDN_USERNAME = 'BUNNY_CDN_USERNAME';
